image_root: "/home/dalu/workspace/walnut_pairing/images"

database:
  host: "localhost"
  port: 5432
  database: "walnut_pairing"
  user: "postgres"
  password: "sa"

cameras:
  FRONT:
    distance_mm: 100.0
    focal_length_px: 1000.0
  BACK:
    distance_mm: 100.0
    focal_length_px: 1000.0
  LEFT:
    distance_mm: 100.0
    focal_length_px: 1000.0
  RIGHT:
    distance_mm: 100.0
    focal_length_px: 1000.0
  TOP:
    distance_mm: 100.0
    focal_length_px: 1000.0
  DOWN:
    distance_mm: 100.0
    focal_length_px: 1000.0

algorithm:
    width_weight: 0.40
    height_weight: 0.35
    thickness_weight: 0.25